version: '3.8'

services:
  ai-news:
    build: .
    ports:
      - "6888:6888"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./cache:/app/cache
      - ./static/audio:/app/static/audio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6888/aizaobao/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: ai-news-network
